package org.example.user;

import org.example.insurance.Insurance;

import javax.persistence.*;
import java.util.Set;

// we need to add anotations Entity and Table because User is entity class used for JPA (Java Persistence API - it is used for ORM (mapping))
@Entity
@Table(name = "users")
public class User {

    @Id // this is the ID value in the table users
    @GeneratedValue(strategy = GenerationType.IDENTITY) // this value is automatically generated by database
    @JoinColumn(unique = true, name = "user_id")
    private Long userId;

    @Column(nullable = false, length = 45, name = "first_name") // basic settings for this value
    private String firstName;

    @Column(nullable = false, length = 45, name = "last_name")
    private String lastName;

    @Column(nullable = false, length = 45, unique = true, name = "email")
    private String email;

    @Column(nullable = false, length = 45, name = "street")
    private String street;

    @Column(nullable = false, length = 45, name = "city")
    private String city;

    @Column(nullable = false, length = 5, name = "postcode")
    private String postcode;

    @Column(nullable = false, length = 14, unique = true, name = "telephone_number")
    private String telephoneNumber;

    @OneToMany(mappedBy="user", cascade = CascadeType.ALL)
    private Set<Insurance> insurance;


    // getters and setters
    public Long getUserId() { return userId; }

    public void setUserId(Long userId) { this.userId = userId; }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                ", street='" + street + '\'' +
                ", city='" + city + '\'' +
                ", postcode='" + postcode + '\'' +
                ", telephoneNumber='" + telephoneNumber + '\'' +
                '}';
    }
}
